### ISSUE TITLE
Container fails to start due to update

### ISSUE THREAD

**Issue by cablespaghetti** [LambdaTest/docker-tunnel#5]
Hi,

Our tunnel container is restarting over and over again due to trying to update:
```
No configuration file found. Proceeding with defaults
INFO	LambdaTest Tunnel version: 3.1.19
INFO	New update available for the tunnel client. Downloading update
INFO	Update successfully installed. Please restart the binary
```

Is there a way to disable the updates so the container can start? In my opinion this should be the default for Docker.

**Comment by cablespaghetti** [comment]
I've found the otherwise undocumented `--skip-upgrade` flag in a blog post, which seems to have worked around the issue. However I strongly think this should be the default for Docker.

**Comment by rishabh-arya95** [comment]
Hi @cablespaghetti  sorry for the inconvenience. We have upgraded our docker tunnel image, there was some bug in our CI pipeline due to which updated image was not uploaded on docker hub. We will be adding a feature in tunnel for optional updates and it will not force-ably update itself.

**Comment by cablespaghetti** [comment]
No problem. Thanks for the response!

**Comment by cybernotic** [comment]
Hi, this seems to be an issue for me:
    [34mINFO[0m     LambdaTest Tunnel version: 3.1.31
    [34mINFO[0m     New update available for the tunnel client. Downloading update
    [34mINFO[0m     Update successfully installed. Please restart the binary
UIs there anything I can do to bypass this?

**Comment by cablespaghetti** [comment]
Have you tried using the `—skip-upgrade` flag mentioned before?
