### ISSUE TITLE
Use ENV vars for configuration

### ISSUE THREAD

**Issue by catherine-swift** [LambdaTest/docker-tunnel#6]
Standard practice for managing configuration of containerized processes is to enable at least some of that configuration to be given via environment variables.  It would be beneficial for the LT tunnel container to accept at least username and password via env vars:
*  `LT_USER`
*  `LT_KEY`

**Comment by Shivanshu-lambdatest** [comment]
Hi, @catherine-swift LT Tunnel does support ENV variables for configuration. Please check out the documentation https://www.lambdatest.com/support/docs/environment-variables-supported-by-lambda-tunnel.
